export enum BackgroundEnum {
  Aurifex = 1,
  Barber_Surgeon,
  Beast_Handler,
  Bonekeeper,
  Cutpurse,
  Fieldwarden,
  Fletchwind,
  Foundling,
  Fungal_Forager,
  Greenwise,
  Half_Witch,
  Hexenbane,
  Jongleur,
  Kettlewright,
  Marchguard,
  Mountebank,
  Outrider,
  Prowler,
  Rill_Runner,
  Scrivener,
}